### ISSUE TITLE
SAM can't accept twice the same parameter.

### ISSUE THREAD

**Issue by Loic-Dumas** [SRGSSR/srgdataprovider-android#42]
## Issue description
SAM can't accept twice the same parameter. During the migration from IL to SAM, we noticed that vector is added twice in calls for nextUrl.

This vector present twice is caused by:
- The vector parameter returned in the next URL 
- The vector added by [OkHttpModule](https://github.com/SRGSSR/srgdataprovider-android/blob/2fea6d6ec932cbfd301c5965b4716ad8aeb76cee/dataprovider-retrofit/src/main/java/ch/srg/dataProvider/integrationlayer/dependencies/modules/OkHttpModule.kt#L34)

### Example
For exemple the call:
https://il-stage.srgssr.ch/integrationlayer/2.0/srf/mediaList/audio/episodesByDateAndChannel/2024-06-06/69e8ac16-4327-4af4-b873-fd5cd6e895a7?pageSize=20&vector=APPPLAY

**result:**
```
{
   "next": "https://il-stage.srgssr.ch/integrationlayer/2.0/srf/mediaList/audio/episodesByDateAndChannel/2024-06-06/69e8ac16-4327-4af4-b873-fd5cd6e895a7?pageSize=20&vector=APPPLAY&next=1",
    "mediaList": ...
}
```

So if the next URL is called with `OkHttpModule`, this call is made. 
https://il-stage.srgssr.ch/integrationlayer/2.0/srf/mediaList/audio/episodesByDateAndChannel/2024-06-06/69e8ac16-4327-4af4-b873-fd5cd6e895a7?pageSize=20&vector=APPPLAY&next=1&vector=APPPLAY

And SAM return this error:
```
{
   "detail": "Failed to convert argument [vector] for value [[APPPLAY, APPPLAY]] due to: Cannot convert an iterable with more than 1 value to a non collection object",
   "type": "sam:error:input_conversion_failed",
   "title": "Input conversion failed",
   "status": 400
}
```

### Note
Before, when this call was made on IL, multiple same parameter was accepted.

## What should be fixed
Don't add the vector parameter in the call if already present in url. 

See [VectorInterceptor](https://github.com/SRGSSR/srgdataprovider-android/blob/2fea6d6ec932cbfd301c5965b4716ad8aeb76cee/dataprovider-retrofit/src/main/java/ch/srg/dataProvider/integrationlayer/utils/VectorInterceptor.kt#L19)

### Solution approach
Two possible approaches:
1. Remove all vector param before adding the right one.
   Pro: Ensure only one vector is sent. 
   Cons: Could change from the vectors before in the url.
2. Do nothing if already contains a vector param.
   Pro: Keep the vector set originally.
   Cons: Assume the original url only contains one vector

## Related issue

See issue in Play: https://srgssr-ch.atlassian.net/browse/PLAYRTS-5545 

### Reproducibility

Always

### Steps to reproduce

1. Call a  next URL with `OkHttpModule`

### Library version

0.10.0

### Operating system

All

### Is there an existing issue for this?

- [X] I have searched existing issues and found no similar bug report.

**Comment by MGaetan89** [comment]
I'm closing this issue, since it was fixed in #43
